[phases.setup]
nixPkgs = ["jdk17", "gradle"]

[phases.build]
cmds = [
  "export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))",
  "echo Using JAVA_HOME=$JAVA_HOME",
  "chmod +x ./gradlew",
  "./gradlew --version",
  "./gradlew clean bootJar -x test -Pproduction --no-daemon"
]

[start]
cmd = "java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-prod} -jar build/libs/app.jar"
