ALTER TABLE user_body_stats
    ADD COLUMN IF NOT EXISTS body_fat_percent DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS mbti VARCHAR(4) NULL;

ALTER TABLE character_profiles
    ADD COLUMN IF NOT EXISTS avatar_seed VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS style_preset VARCHAR(32) NOT NULL DEFAULT 'BALANCED',
    ADD COLUMN IF NOT EXISTS reroll_count INT NOT NULL DEFAULT 0;
