ALTER TABLE attendance_logs
    ADD COLUMN IF NOT EXISTS media_urls VARCHAR(4000) NULL,
    ADD COLUMN IF NOT EXISTS shared TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS share_slug VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS cheer_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS report_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hidden_by_admin TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS edit_count INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_edited_at DATETIME NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_attendance_logs_share_slug
    ON attendance_logs (share_slug);
